In [1]:
import numpy as np

### Steps for SVD ( U, S, V).

#### 1) Take matrix A.
#### 2) Calculate transpose of a matrix AT.
#### 3) U=A . AT.

#### 4) Calculate eigenvalues and eigenvectors for U.
#### 5) Sort eigenvalues in descending order.
#### 6) Make corresponding eigenvectors. 
#### 7) Normalize above  matrix.


#### 8) V = AT . A
#### 9) Repeat 4 to 7 for V matrix.

#### 10) Create S matrix by taking eigenvalues from U or V. 
#### 11) convert it into a diagonal matrix and take square root of non zero eigenvalues.


In [2]:
A=np.array([[7,2],[3,4],[5,3]])
A

array([[7, 2],
       [3, 4],
       [5, 3]])

In [3]:
U,S,V=np.linalg.svd(A)

In [4]:
U.shape,S.shape

((3, 3), (2,))

In [6]:
# np.dot(U,np.diag(S))

In [5]:
np.dot(np.dot(U[:,:2],np.diag(S)),V)

array([[7., 2.],
       [3., 4.],
       [5., 3.]])

In [6]:
A

array([[7, 2],
       [3, 4],
       [5, 3]])

In [7]:
np.diag(S)

array([[10.25142677,  0.        ],
       [ 0.        ,  2.62835484]])

In [8]:
np.dot(np.dot(U[:,:1],S[0]),V[:1,:])

array([[6.26013786, 3.37310746],
       [3.99532758, 2.15277516],
       [5.12773272, 2.76294131]])

In [9]:
A

array([[7, 2],
       [3, 4],
       [5, 3]])

In [10]:
S[0]/np.sum(S) # 79 percent of variation in the data is explained by first 
               # singular vector

0.7959317231047445

In [11]:
S[1]/np.sum(S) # 20 percent of variation in the data is explained by first 
               # singular vector

0.20406827689525547

In [14]:
# from sklearn.decomposition import TruncatedSVD
# sv=TruncatedSVD(1)
# sv.fit_transform(A)

In [12]:
A=np.array([
    [1,1,1,0,0],
    [3,3,3,0,0],
    [4,4,4,0,0],
    [5,5,5,0,0],
    [0,2,0,4,4],
    [0,0,0,5,5],
    [0,1,0,2,2]
])

In [13]:
U,S,V=np.linalg.svd(A)

In [14]:
U.shape

(7, 7)

In [15]:
V.shape

(5, 5)

In [16]:
S.round(3)

array([12.481,  9.509,  1.346,  0.   ,  0.   ])

In [17]:
red_A=np.dot(np.dot(U[:,:3],np.diag(S[:3])),V[:3,:])

In [18]:
red_A.round(3)

array([[ 1.,  1.,  1., -0., -0.],
       [ 3.,  3.,  3., -0., -0.],
       [ 4.,  4.,  4., -0., -0.],
       [ 5.,  5.,  5., -0., -0.],
       [-0.,  2., -0.,  4.,  4.],
       [-0.,  0., -0.,  5.,  5.],
       [-0.,  1., -0.,  2.,  2.]])

In [19]:
red_A=np.dot(np.dot(U[:,:2],np.diag(S[:2])),V[:2,:])
red_A.round(1)

array([[ 1. ,  1. ,  1. , -0. , -0. ],
       [ 3. ,  3. ,  3. , -0. , -0. ],
       [ 4. ,  4. ,  4. , -0. , -0. ],
       [ 5. ,  5.1,  5. , -0. , -0. ],
       [ 0.4,  1.3,  0.4,  4.1,  4.1],
       [-0.4,  0.7, -0.4,  4.9,  4.9],
       [ 0.2,  0.6,  0.2,  2. ,  2. ]])

In [20]:
import pandas as pd
A1=pd.DataFrame(A,columns=['m1','m2','m3','m4','m5'],
               index=['u1','u2','u3','u4','u5','u6','u7'])

C:\Anaconda\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [21]:
A1

m1  m2  m3  m4  m5
u1   1   1   1   0   0
u2   3   3   3   0   0
u3   4   4   4   0   0
u4   5   5   5   0   0
u5   0   2   0   4   4
u6   0   0   0   5   5
u7   0   1   0   2   2

In [22]:
pd.DataFrame(U[:,:2].round(2),columns=['concept1','concept2'],
               index=['u1','u2','u3','u4','u5','u6','u7'])

concept1  concept2
u1     -0.14     -0.02
u2     -0.41     -0.07
u3     -0.55     -0.09
u4     -0.69     -0.12
u5     -0.15      0.59
u6     -0.07      0.73
u7     -0.08      0.30

In [23]:
pd.DataFrame(V[:2,:].round(2),
            columns=['m1','m2','m3','m4','m5'],
            index=['concept1','concept2'])

m1    m2    m3    m4    m5
concept1 -0.56 -0.59 -0.56 -0.09 -0.09
concept2 -0.13  0.03 -0.13  0.70  0.70

In [27]:
import pandas as pd


In [28]:
data=pd.read_csv('breast_cancer.csv')

In [29]:
data.shape

(569, 32)

In [30]:
data.head(2)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0  842302         M        17.99         10.38           122.8     1001.0   
1  842517         M        20.57         17.77           132.9     1326.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33            184.6      2019.0   
1  ...         24.99          23.41            158.8      1956.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  

[2 rows x 32 columns]

In [31]:
inp=data.drop(['id','diagnosis'],axis=1)
out=data['diagnosis']

In [32]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(inp,out,test_size=0.3,
                                           random_state=48)

In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

rf=RandomForestClassifier(random_state=0)
rf.fit(xtrain,ytrain)
ypred=rf.predict(xtest)
print('Without any dimentionality reduction')
print('The number of features are:',inp.shape[1])
print('######################################')
print(classification_report(ytest,ypred))

Without any dimentionality reduction
The number of features are: 30
######################################
              precision    recall  f1-score   support

           B       0.94      0.95      0.94        95
           M       0.93      0.92      0.93        76

    accuracy                           0.94       171
   macro avg       0.94      0.93      0.93       171
weighted avg       0.94      0.94      0.94       171



In [34]:
# Apply PCA 
# Scaling is must for PCA

In [35]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
inp_sc=sc.fit_transform(inp)

In [36]:
from sklearn.decomposition import PCA
pc=PCA()
pca_inp=pc.fit_transform(inp_sc)

In [37]:
inp_sc.shape,pca_inp.shape

((569, 30), (569, 30))

In [38]:
pd.DataFrame(inp_sc).head(1)

0         1         2         3         4         5         6   \
0  1.097064 -2.073335  1.269934  0.984375  1.568466  3.283515  2.652874   

         7         8         9   ...       20        21        22        23  \
0  2.532475  2.217515  2.255747  ...  1.88669 -1.359293  2.303601  2.001237   

         24        25        26        27        28        29  
0  1.307686  2.616665  2.109526  2.296076  2.750622  1.937015  

[1 rows x 30 columns]

In [39]:
pd.DataFrame(pca_inp).head(1)

0         1         2         3        4         5        6   \
0  9.192837  1.948583 -1.123166  3.633731 -1.19511  1.411424  2.15937   

         7         8         9   ...        20       21        22        23  \
0 -0.398407 -0.157118 -0.877402  ...  0.096515  0.06885  0.084519 -0.175256   

        24        25        26        27        28        29  
0 -0.15102 -0.201503 -0.252585 -0.033914  0.045648 -0.047169  

[1 rows x 30 columns]

In [40]:
#eigen values
pd.DataFrame(pc.explained_variance_).round(2)

0
0   13.30
1    5.70
2    2.82
3    1.98
4    1.65
5    1.21
6    0.68
7    0.48
8    0.42
9    0.35
10   0.29
11   0.26
12   0.24
13   0.16
14   0.09
15   0.08
16   0.06
17   0.05
18   0.05
19   0.03
20   0.03
21   0.03
22   0.02
23   0.02
24   0.02
25   0.01
26   0.01
27   0.00
28   0.00
29   0.00

In [41]:
pd.DataFrame(pc.explained_variance_ratio_).round(2)

0
0   0.44
1   0.19
2   0.09
3   0.07
4   0.05
5   0.04
6   0.02
7   0.02
8   0.01
9   0.01
10  0.01
11  0.01
12  0.01
13  0.01
14  0.00
15  0.00
16  0.00
17  0.00
18  0.00
19  0.00
20  0.00
21  0.00
22  0.00
23  0.00
24  0.00
25  0.00
26  0.00
27  0.00
28  0.00
29  0.00

In [42]:
cum_var=np.cumsum(pc.explained_variance_ratio_)
(cum_var<0.95).sum()

9

In [43]:
cum_var=np.cumsum(pc.explained_variance_ratio_)
(cum_var<0.95).sum()
# First 9 pc's itself reproducing 95 percent variance of the original data
# Hence use only 9 pcs and build the ML model

9

In [44]:
pca_inp_red=pca_inp[:,:9]

In [45]:
pca_inp_red.shape

(569, 9)

In [46]:
pca_inp_red=pca_inp[:,:9]
xtrain,xtest,ytrain,ytest=train_test_split(pca_inp_red,out,test_size=0.3,
                                           random_state=48)

rf=RandomForestClassifier(random_state=0)
rf.fit(xtrain,ytrain)
ypred=rf.predict(xtest)
print('With PCA components reduction')
print('The number of features are:',pca_inp_red.shape[1])
print('######################################')
print(classification_report(ytest,ypred))

With PCA components reduction
The number of features are: 9
######################################
              precision    recall  f1-score   support

           B       0.94      0.96      0.95        95
           M       0.95      0.92      0.93        76

    accuracy                           0.94       171
   macro avg       0.94      0.94      0.94       171
weighted avg       0.94      0.94      0.94       171



In [47]:
from sklearn.decomposition import TruncatedSVD
sv=TruncatedSVD(n_components=29)
svd_inp=sv.fit_transform(inp_sc)

In [48]:
inp_sc.shape,svd_inp.shape

((569, 30), (569, 29))

In [49]:
cum_var=np.cumsum(sv.explained_variance_ratio_)
(cum_var<0.95).sum()

9

In [50]:
svd_inp_red=svd_inp[:,:9]
xtrain,xtest,ytrain,ytest=train_test_split(svd_inp_red,out,test_size=0.3,
                                           random_state=48)

rf=RandomForestClassifier(random_state=0)
rf.fit(xtrain,ytrain)
ypred=rf.predict(xtest)
print('With SVD components reduction')
print('The number of features are:',svd_inp_red.shape[1])
print('######################################')
print(classification_report(ytest,ypred))

With SVD components reduction
The number of features are: 9
######################################
              precision    recall  f1-score   support

           B       0.94      0.96      0.95        95
           M       0.95      0.92      0.93        76

    accuracy                           0.94       171
   macro avg       0.94      0.94      0.94       171
weighted avg       0.94      0.94      0.94       171



In [51]:
rf.feature_importances_

array([0.61903292, 0.09047905, 0.08759245, 0.03335702, 0.04723169,
       0.03781845, 0.03451532, 0.02216139, 0.02781172])

In [52]:
list(pd.DataFrame(svd_inp_red).columns)

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [53]:
pd.DataFrame(sv.components_).shape

(29, 30)

In [54]:
# Singular Vectors
pd.DataFrame(sv.components_).head(1)

0         1         2         3        4         5       6   \
0  0.218902  0.103725  0.227537  0.220995  0.14259  0.239285  0.2584   

         7         8         9   ...        20        21       22        23  \
0  0.260854  0.138167  0.064363  ...  0.227997  0.104469  0.23664  0.224871   

         24        25        26        27        28        29  
0  0.127953  0.210096  0.228768  0.250886  0.122905  0.131784  

[1 rows x 30 columns]

In [55]:
inp.columns

Index(['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')